# Generated by Django 4.2.7 on 2023-11-10 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='время')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(default=24, verbose_name='периодичность в часах')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('duration', models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
